name: Guido Fokkema Fotografie
favicon: null
layout_spectrum: 0.25451
typography_spectrum: 0.25782
title: Guido Fokkema Fotografie
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151412'
    - '#313717'
    - '#5e601f'
    - '#a3923f'
    - '#b0c4ca'
  brandStrength: 0.25
  lightness: 0.5178013304248452
  saturation: 0.625
  rhythmicContrast: 0
purpose: []
